# Generated by Django 4.1.6 on 2023-02-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_votes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='action',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='votes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
